AZURE_SEARCH_KEY: ${AZURE_SEARCH_KEY}
AZURE_SEARCH_ENDPOINT: ${AZURE_SEARCH_ENDPOINT}

PRESIDIO_ANALYZER_ENDPOINT: ${PRESIDIO_ANALYZER_ENDPOINT}
PRESIDIO_ANONYMIZER_ENDPOINT: ${PRESIDIO_ANONYMIZER_ENDPOINT}
spring:
  ai:
    azure:
      openai:
        endpoint: ${AZURE_OPENAI_ENDPOINT}
        api-key: ${AZURE_OPENAI_KEY}